import { memo } from 'react'


export default memo(() => {
    return (<>
        <div>
            <div >
                <p className="mt-4">
                    <strong><span style={{ fontSize: "18px" }}>购物退换货政策</span></strong></p>
                <p><span style={{ fontFamily: "宋体" }}><br /></span></p><p>&nbsp;</p><p>退货时间：商品<span style={{ fontFamily: "Calibri" }}>&lt;30</span><span style={{ fontFamily: "宋体" }}>日</span></p><p>符合退款政策的商品，您可以致电&nbsp;<span style={{ fontFamily: "宋体" }}>客服电话申请退货退款。如果售后人员同意了您的退款申请，退款将按照原路径退回。退款到账时间为</span><span style={{ fontFamily: "Calibri" }}>1~15</span><span style={{ fontFamily: "宋体" }}>个工作日内。</span></p><p>&nbsp;</p><p>&nbsp;</p><p>Q<span style={{ fontFamily: "宋体" }}>：正常商品什么时候才能申请退货？</span></p><p>当您签收商品<span style={{ fontFamily: "Calibri" }}>7</span><span style={{ fontFamily: "宋体" }}>天内，您可以联系我们的在线客服申请售后服务提交退货申请（需保证退货商品不影响二次销售）。</span></p><p>&nbsp;</p><p>Q<span style={{ fontFamily: "宋体" }}>：哪些情况下可以申请退货退款？</span></p><p>1.<span style={{ fontFamily: "宋体" }}>商品在运输过程中造成的破损、液漏、性能故障，经售后人员核查情况属实；</span></p><p>2.<span style={{ fontFamily: "宋体" }}>商品丢件、漏发，经快递人员证明及售后人员核查情况属实；</span></p><p>3.<span style={{ fontFamily: "宋体" }}>实际收到商品与订购商品不符，经客户提供证明及售后人员核查情况属实；</span></p><p>4.<span style={{ fontFamily: "宋体" }}>收到的商品已过保质期，经售后人员核查情况属实；</span></p><p>5.<span style={{ fontFamily: "宋体" }}>若因宠物过敏反应问题导致的退货，需要提供医院的相关证明，经售后人员核查情况属实；</span></p><p>6<span style={{ fontFamily: "宋体" }}>自发货日起，用户超过</span><span style={{ fontFamily: "Calibri" }}>30</span><span style={{ fontFamily: "宋体" }}>天未收到商品，经售后人员核查情况属实，客户可申请退款；</span></p>
                <p>7.<span style={{ fontFamily: "宋体" }}>客户个人原因导致的退换货，未使用且不影响二次销售，经售后人员核查情况属实；</span></p><p>&nbsp;</p><p>Q<span style={{ fontFamily: "宋体" }}>：如果收到商品不满意，能申请换货吗？</span></p><p>由于海关监管政策严格，保税仓售出的商品暂不支持换货服务。</p><p>&nbsp;</p><p>Q<span style={{ fontFamily: "宋体" }}>：办理退货周期多久？</span></p><p>一般情况下，自您提交退货申请之日起<span style={{ fontFamily: "Calibri" }}>3</span><span style={{ fontFamily: "宋体" }}>天内为您处理完成。在办理退款前，请确保您的商品符合退货政策。如果售后人员同意了您的退款申请，退款将按照原路径退回。</span></p><p>&nbsp;</p><p>Q<span style={{ fontFamily: "宋体" }}>：为什么售后申请没有审核通过？</span></p><p>您可以联系我们的在线客服咨询审核未通过原因。</p><p>&nbsp;</p><p>Q<span style={{ fontFamily: "宋体" }}>：哪些商品不适用退货政策：</span></p>
                <p>1.<span style={{ fontFamily: "宋体" }}>任何非麦萌全球购出售的商品；</span></p>
                <p>2.<span style={{ fontFamily: "宋体" }}>商品已使用影响二次销售，盒装</span><span style={{ fontFamily: "Calibri" }}>/</span><span style={{ fontFamily: "宋体" }}>箱装等整装商品一经拆封将不支持退货；</span></p>
                <p>3.<span style={{ fontFamily: "宋体" }}>超过受理时限（签收后</span><span style={{ fontFamily: "Calibri" }}>7</span><span style={{ fontFamily: "宋体" }}>天内未提交申请将不能申请售后）；</span></p>
                <p>4.<span style={{ fontFamily: "宋体" }}>由于运输过程中的不可抗拒因素，商品出现轻微破损，但不影响正常使用；</span></p>
                <p>5.<span style={{ fontFamily: "宋体" }}>商品出售时，已在商品相关页面明示保质期将到；</span></p>
                <p>6.<span style={{ fontFamily: "宋体" }}>任何因客户的非正常使用及保管，导致出现商品质量问题的；</span></p>
                <p>7.<span style={{ fontFamily: "宋体" }}>礼包或者套装中的商品不可以部分退换货；</span></p>
                <p>8.<span style={{ fontFamily: "宋体" }}>其他依法不办理退货的；</span></p><p>9.<span style={{ fontFamily: "宋体" }}>部分商品除外。</span></p><p>&nbsp;</p>
                <p>温馨提示：</p>
                <p>1.<span style={{ fontFamily: "宋体" }}>因拍摄灯光及不同显示器色差等问题可能造成商品图片与实物有色差，一切以实物为准；</span></p>
                <p>2.<span style={{ fontFamily: "宋体" }}>商品签收时请与快递人员当面开箱验货，如果出现质量问题，您可以当面拒收；</span></p><p>3.<span style={{ fontFamily: "宋体" }}>建议妥善保管商品的外包装至少</span><span style={{ fontFamily: "Calibri" }}>15</span><span style={{ fontFamily: "宋体" }}>天；</span></p><p>4.<span style={{ fontFamily: "宋体" }}>由于海关监管要求，暂不支持换货服务，如有需要您可以重新购买；</span></p>
                <p>5.<span style={{ fontFamily: "宋体" }}>退货时，一律不接受客户的到付邮件或者平邮邮件。</span></p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;运费退还说明：</p><p>&nbsp;</p><table align="center"><tbody><tr><td valign="top"><p>退货类别</p></td><td valign="top"><p>运费责任人</p></td><td valign="top"><p>备注</p></td></tr><tr><td ><p>商品质量</p><p>包装破损</p><p>错漏发货</p></td><td ><p><span style={{ fontFamily: "宋体" }}>宠物商城</span></p></td><td valign="top"><p>客户需要出具相关质量检测报告或经品牌方（<span style={{ fontFamily: "宋体" }}>宠物商城</span>商家）确认质量问题，并提供相关照片证明以及相关检测报告。拒收、反馈时间离签收时间超过7<span style={{ fontFamily: "宋体" }}>天</span>的将不予受理此需求。</p></td></tr><tr><td ><p>第三方原因导致商品破损</p></td><td ><p>第三方（物流）</p></td><td valign="top"><p>用户需要提供签收包裹时的多角度外包装图，实物破损图，商品清单图，<span style={{ fontFamily: "Calibri" }}></span><span style={{ fontFamily: "宋体" }}>宠物商城</span>售后人员核实后将受理退货申请。拒收、反馈时间离签收时间超过7<span style={{ fontFamily: "宋体" }}>天</span>的将不予受理此需求。</p></td></tr><tr><td ><p>其他原因</p></td><td ><p>客户</p></td><td valign="top"><p>拒收、反馈时间离签收时间超过7<span style={{ fontFamily: "宋体" }}>天</span>的将不予受理此需求</p></td></tr></tbody></table><p>&nbsp;</p>
                <p>退换货产生的运费<br/>1.<span style={{ fontFamily: "宋体" }}>若选择单独退换货，运费还请先行垫付</span><span style={{ fontFamily: "Calibri" }}></span><span style={{ fontFamily: "宋体" }}>宠物商城快递（不超过</span><span style={{ fontFamily: "Calibri" }}>15</span><span style={{ fontFamily: "宋体" }}>公斤&nbsp;</span><span style={{ fontFamily: "Calibri" }}>5</span><span style={{ fontFamily: "宋体" }}>元</span><span style={{ fontFamily: "Calibri" }}>/</span><span style={{ fontFamily: "宋体" }}>次；</span><span style={{ fontFamily: "Calibri" }}>15</span><span style={{ fontFamily: "宋体" }}>公斤或以上&nbsp;</span><span style={{ fontFamily: "Calibri" }}>30</span><span style={{ fontFamily: "宋体" }}>元</span><span style={{ fontFamily: "Calibri" }}>/</span><span style={{ fontFamily: "宋体" }}>次），外包快递（根据实际情况为准）。</span></p><p>&nbsp;</p><p>2.<span style={{ fontFamily: "宋体" }}>若</span><span style={{ fontFamily: "Calibri" }}></span><span style={{ fontFamily: "宋体" }}>宠物商城快递选择下次购物时订单满</span><span style={{ fontFamily: "Calibri" }}>38</span><span style={{ fontFamily: "宋体" }}>元，顺便退换货，运费全免。但请注意的是需要说明您退换的是什么商品，以便我们安排合适的车辆。（仅限</span><span style={{ fontFamily: "Calibri" }}></span><span style={{ fontFamily: "宋体" }}>宠物商城快递覆盖范围有效）</span><br/></p><p>&nbsp;</p><p>退换货细则<br/>1.<span style={{ fontFamily: "宋体" }}>客户在订单中心申请退换货申请或者致电</span><span style={{ fontFamily: "宋体" }}>客服电话联。</span></p>
                <p>2.<span style={{ fontFamily: "宋体" }}>客服与您沟通并记录。</span></p>
                <p>3.<span style={{ fontFamily: "宋体" }}>将退货商品寄回（地址见上），随包裹写明退货的订单号和退货要求（如有赠品、票据等需一并退回）。</span></p><p>4.<span style={{ fontFamily: "宋体" }}>收到您的退货包裹后，相关专业人员检查商品是否完好。</span></p>
                <p>5.<span style={{ fontFamily: "宋体" }}>完成退货商品退款，自动退款到账户余额。您可以自主选择提现到支付宝、银行卡等各个账。</span></p>
                <p>6.退货请大家不要发到付，我们暂不不支持。</p><p>&nbsp;</p><p>退换货处理</p><p>对于退回的有瑕疵商品，全部采用清仓打折处理，不再进行正常销售。&nbsp;</p>
                </div>
        </div>
    </>)
})